title: Fabylo Theme
baseURL: /
params:
  footer:
    content: Fabylo. All rights reserved.
    has_nav: true
    has_social: true
    has_subscribe: true
    links: []
    logo_img: ''
    nav_title: Fabylo
    social_title: Community
    subscribe_content: Stay up to date with our latest developments.
    subscribe_title: Subscribe
    tagline: FABYLO
  header:
    has_nav: true
    logo_img: ''
    title: Fabylo
    menu:
      actions: []
  palette: green
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
